version: "3.5"
 
services:
  wordpress:
    image: insermbiblio/wordpress:6.2.0-apache
    ports:
        - 8080:8080
    links:
        - db:mysql
    environment:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
        - wordpress:/var/www/html
    restart: always
    networks:
      insfrontend :
      insbackend :
        aliases:
          - wordpress

  db:
    image: mariadb:10.0
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PORT: 3305
        TERM: dumb
    volumes:
        - /applis/insermbib/home/mariadb:/var/lib/mysql
    restart: always
    networks:
      insbackend :
        aliases:
          - mysql

volumes:
  wordpress: # Contient le code HTML pour wordpress

networks:
  insbackend:
    driver: bridge
    name: insbackend
  insfrontend:
    driver: bridge
    name: insfrontend
