version: "2"
 
services:
  wordpress:
    image: insermbiblio/wordpress:5.4.1-apache
    ports:
        - 8080:8080
    links:
        - db:mysql
    environment:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
        - wordpress:/var/www/html
    restart: always

  db:
    image: mariadb:10.0
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PORT: 3305
        TERM: dumb
    volumes:
        - /applis/insermbib/home/mariadb:/var/lib/mysql
    restart: always
    
volumes:
  wordpress: # Contient le code HTML pour wordpress
